services:
  - docker

jobs:
  include:
    - stage: confd-test
      before_install:
        - wget https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64
        - sudo mkdir -p /opt/confd/bin
        - sudo mv confd-0.16.0-linux-amd64 /opt/confd/bin/confd
        - sudo chmod +x /opt/confd/bin/confd
        - export PATH="$PATH:/opt/confd/bin"

      script:
        - make update-props-dryrun
        - make update-props

    - stage: tests
      name: "Sonar"
      language: java
      install: true
      jdk: openjdk8
      if: fork = false

      addons:
        sonarcloud:
          organization: "open-kilda"
          token:
            secure: "ekznTpLDEd2x5SMcxPE609zYDv+dDMbgyQOWGjYdRsMrjeAqJvlRPz3NFqqLK0+RXzGYO+TOfZf1rUpv5B47n4j1U8O5wDoXw5ZXAXM8hHNbz4qqMZdfXAOyTGMsqrBHLC0omFxWNfTc9QMQtdWbqgSU3KzGDg/0J3pypQoCAP52e5bSzSBchVXR5xmInaFYlGHZfsZpKuSavRki3hvwlM1N6F3abQQgQq3XVH05KHerhv/3AQ9gjHv4O0K1oRt0CJo1TztMIlRB70MY4JMv8Bpf09PzteP/fjZBlB7vIKZ1TQOph9mMYJ8guXatTvZ7Ym2Lkihq2/KvG6p650oeQxTE0b4j6aqbZPN+C3o9INMnA80chZzBySGjYleNOBPXl5bDouW94HKfvBdQFfFRFuHS280fVrYvO11IYdkglcxnk3YhMcJO/iJuH7IiUeWLQ6vpVOPJzDBt7QQqhTFWySidEnmQdnlotQigXpgZ9h98qyHR3fXVFAArWX1bcSA9WAIZHAFJwjVSimVCq5SJDPhgkcyyzauInNiFb1fPMjDscYfCXpK7ws9ydzMTVV+kQ+2x8JO9jJwDOzUkGHV83zheO3TzSCfuANBhP1GwkcSVvgEcrc5A5eosbC3DDcQpK7KRX7QHKsnSetqovh8MoFeNG4nYObOC4oyPZT6AXf4="

      before_install:
        - wget https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64
        - sudo mkdir -p /opt/confd/bin
        - sudo mv confd-0.16.0-linux-amd64 /opt/confd/bin/confd
        - sudo chmod +x /opt/confd/bin/confd
        - export PATH="$PATH:/opt/confd/bin"

      before_cache:
        - sudo chown -R travis:travis $HOME/.m2/repository
        - sudo chown -R travis:travis $HOME/.sonar/cache
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      script:
        - export MAVEN_OPTS="$MAVEN_OPTS -DinteractiveMode=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
        - mkdir -p ~/.gradle && echo "org.gradle.jvmargs=-Xmx4096M" >> ~/.gradle/gradle.properties
        - make sonar

      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.sonar/cache'
          - '$HOME/.gradle/caches/'
          - '$HOME/.gradle/wrapper/'

    - stage: tests
      name: "Unit"
      language: java
      jdk: openjdk8

      before_install:
        - wget https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64
        - sudo mkdir -p /opt/confd/bin
        - sudo mv confd-0.16.0-linux-amd64 /opt/confd/bin/confd
        - sudo chmod +x /opt/confd/bin/confd
        - export PATH="$PATH:/opt/confd/bin"

      before_cache:
        - sudo chown -R travis:travis $HOME/.m2/repository
        - sudo chown -R travis:travis $HOME/.sonar/cache
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      script:
        - export MAVEN_OPTS="$MAVEN_OPTS -DinteractiveMode=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
        - mkdir -p ~/.gradle && echo "org.gradle.jvmargs=-Xmx4096M" >> ~/.gradle/gradle.properties
        - make unit

      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.sonar/cache'
          - '$HOME/.gradle/caches/'
          - '$HOME/.gradle/wrapper/'
