[template]
src = "floodlight-modules/floodlightkilda.properties.tmpl"
dest = "src-java/floodlight-service/floodlight-modules/src/main/resources/floodlightkilda.properties"
keys = [ "/" ]
mode = "0644"
