Internal data
* ISL reference
* BFD descriptor
* switch online status listener
* port status listener
* BFD properties
* action
* tear down flag

Internal signals
* action-success
* action-fail
* ready

Input signals
* online
* offline
* port-up
* port-down
* enable (ISL-FSM)
* disable (ISL-FSM)
* speaker-response

Output signals
* bfd-up
* bfd-down
* bfd-fail
* bfd-kill

@startuml bfd-port-FSM
title BFD session FSM

[*] --> ENTER
note right of ENTER
    The system must receive one of the events
    that lead out of this state right after FSM was
    created. i.e. FSM must not stay in this state.
end note

ENTER --> PREPARE : enable
ENTER --> REMOVING : disable
ENTER : exit / copy BFD-discriminator from context

PREPARE : enter / allocate(lock) BFD-discriminator
PREPARE : enter / [isOnline] make BFD-setup action and fire ready
PREPARE --> CREATING : ready
PREPARE --> HOUSEKEEPING : disable
PREPARE : online / make BFD-setup action and fire ready

CREATING : enter / clean port status transitions
CREATING --> ACTIVE : action-success
CREATING --> REMOVING : disable

state ACTIVE {
    [*] --> WAIT_STATUS

    WAIT_STATUS --> UP : port-up
    WAIT_STATUS --> DOWN : port-down
    WAIT_STATUS : enter / pull port status transition

    UP -r-> DOWN : port-down
    UP : enter / emit bfd-up

    DOWN -l-> UP : port-up
    DOWN : enter / emit bfd-down
}
ACTIVE : enter / save properties into DB
ACTIVE --> REMOVING : disable
ACTIVE : offline / emit bfd-kill
ACTIVE : offline / clean port status transitions
ACTIVE : exit / emit bfd-kill

REMOVING : enter / set tear down flag
REMOVING : enter / [isOnline] make BFD-remove action
REMOVING --> HOUSEKEEPING : action-success
REMOVING : online / make BFD-remove action
REMOVING : disable / [isOnline] make BFD-remove action
REMOVING : action-fail / report fail

HOUSEKEEPING : enter / release BFD-descriptor
HOUSEKEEPING --> [*] : next

@enduml
